apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: backend-fsx-ontap-nas
  namespace: trident
spec:
  version: 1
  backendName: fsx-ontap
  storageDriverName: ontap-nas
  managementLIF: <<management-ip>>
  dataLIF: <<management-ip>>
  svm: SVM1
  credentials:
    name: backend-fsx-ontap-nas-secret
