apiVersion: v1
kind: Pod
metadata:
  name: mysql-client
spec:
  containers:
  - name: mysql-container
    image: registry.redhat.io/rhel9/mysql-80:1-315.1716477796
    command:
      - sh
      - -c
      - sleep infinity
    imagePullPolicy: IfNotPresent
